OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET UTF8
INFILE regdatatotal.csv
INTO TABLE VDP.REGDATATOTAL
REPLACE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(
ID SEQUENCE (MAX,1),
MARKET,
PARTNER,
PARTNER_LINK_STATUS,
TOTAL_REGISTRATIONS
)
